version: 1.0.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: RazorDatabase.sln

after_test:
  - ps: .\nuget-pack.ps1

artifacts:
  - path: RazorDatabase\bin\Release\RazorDatabase.dll
    name: RazorDatabase.dll
  - path: 'RazorDatabase\*.nupkg'